### ISSUE TITLE
Script is not effective anymore

### ISSUE THREAD

**Issue by dschwen** [tsak/spon-remove-adblock#1]
`document.querySelectorAll('.ua-detected')` does not match any node.

**Comment by tsak** [comment]
I've noticed it too. I'll see if I can fix it.

**Comment by dschwen** [comment]
It looks like their script also inhibits scrolling now even if the overlay is removed. I have not managed to track down which eventhandler is responsible for that (or if they are using overflow: none / height: ... CSS tricks). Cool avatar icon by the way!

**Comment by tsak** [comment]
Just fixed it. Works on my side. Let me know if it works for you and I'll close the issue.

**Comment by tsak** [comment]
You can re-install by clicking the install link again:

[spon-adblock-remover.user.js](https://github.com/tsak/spon-remove-adblock/raw/master/spon-adblock-remover.user.js)

**Comment by dschwen** [comment]
Thanks, will try later this afternoon.

**Comment by dschwen** [comment]
Nice, works for me, too, now!
